/**
 * Neo4j service — persists and queries the exposure tree graph (Patient
 * Zero + exposed persons) generated by the "generate exposure graph" chat
 * flow, for the Exposure Graph and Watch List pages.
 *
 * Docs: https://neo4j.com/docs/javascript-manual/current/
 */

import neo4j, { type Driver } from "neo4j-driver";
import type { ExposedPersonNode, ExposureTreeGraphData } from "@/types";

const NEO4J_URI = process.env.NEO4J_URI;
const NEO4J_USERNAME = process.env.NEO4J_USERNAME;
const NEO4J_PASSWORD = process.env.NEO4J_PASSWORD;
const NEO4J_DATABASE = process.env.NEO4J_DATABASE;

const PATIENT_ZERO_ID = "patient-zero";

let driver: Driver | null = null;

function getDriver(): Driver {
  if (!NEO4J_URI || !NEO4J_USERNAME || !NEO4J_PASSWORD) {
    throw new Error("NEO4J_URI, NEO4J_USERNAME, and NEO4J_PASSWORD must all be set");
  }
  if (!driver) {
    driver = neo4j.driver(NEO4J_URI, neo4j.auth.basic(NEO4J_USERNAME, NEO4J_PASSWORD));
  }
  return driver;
}

function getSession() {
  return getDriver().session(NEO4J_DATABASE ? { database: NEO4J_DATABASE } : undefined);
}

export async function storeExposureGraph(graphData: ExposureTreeGraphData): Promise<void> {
  const session = getSession();
  try {
    await session.run(
      `MERGE (p0:Person {id: $id})
       SET p0.label = $label, p0.description = $description, p0.wearing = $wearing`,
      {
        id: PATIENT_ZERO_ID,
        label: graphData.patientZero.label,
        description: graphData.patientZero.description,
        wearing: graphData.patientZero.wearing,
      }
    );

    for (const person of graphData.exposedPersons) {
      await session.run(
        `MERGE (p:Person {id: $id})
         SET p.label = $label,
             p.description = $description,
             p.wearing = $wearing,
             p.appearances = $appearances,
             p.distance = $distance,
             p.timeNearPatientZero = $timeNearPatientZero,
             p.riskLevel = $riskLevel
         WITH p
         MATCH (p0:Person {id: $patientZeroId})
         MERGE (p0)-[e:EXPOSED_TO]->(p)
         SET e.duration = $timeNearPatientZero,
             e.distance = $distance,
             e.riskLevel = $riskLevel,
             e.appearances = $appearances`,
        {
          id: person.id,
          label: person.label,
          description: person.description,
          wearing: person.wearing,
          appearances: person.appearances,
          distance: person.distanceFromPatientZero,
          timeNearPatientZero: person.timeNearPatientZero,
          riskLevel: person.riskLevel,
          patientZeroId: PATIENT_ZERO_ID,
        }
      );
    }
  } catch (error) {
    console.error("[neo4j] storeExposureGraph failed:", error);
  } finally {
    await session.close();
  }
}

export async function getExposureGraph(): Promise<ExposureTreeGraphData | null> {
  const session = getSession();
  try {
    const patientZeroResult = await session.run(
      `MATCH (p0:Person {id: $id}) RETURN p0`,
      { id: PATIENT_ZERO_ID }
    );
    if (patientZeroResult.records.length === 0) {
      return null;
    }

    const exposedResult = await session.run(
      `MATCH (p0:Person {id: $id})-[e:EXPOSED_TO]->(p:Person)
       RETURN p, e`,
      { id: PATIENT_ZERO_ID }
    );

    const p0 = patientZeroResult.records[0].get("p0").properties;
    const exposedPersons: ExposedPersonNode[] = exposedResult.records.map((record) => {
      const p = record.get("p").properties;
      const e = record.get("e").properties;
      return {
        id: p.id,
        label: p.label,
        description: p.description,
        wearing: p.wearing,
        appearances: toNumber(p.appearances ?? e.appearances),
        distanceFromPatientZero: p.distance ?? e.distance,
        timeNearPatientZero: toNumber(p.timeNearPatientZero ?? e.duration),
        riskLevel: p.riskLevel ?? e.riskLevel,
      };
    });

    if (exposedPersons.length === 0) {
      return null;
    }

    return {
      patientZero: {
        id: p0.id,
        label: p0.label,
        description: p0.description,
        wearing: p0.wearing,
      },
      exposedPersons,
    };
  } catch (error) {
    console.error("[neo4j] getExposureGraph failed:", error);
    return null;
  } finally {
    await session.close();
  }
}

export async function clearExposureGraph(): Promise<void> {
  const session = getSession();
  try {
    await session.run(`MATCH (n) DETACH DELETE n`);
  } catch (error) {
    console.error("[neo4j] clearExposureGraph failed:", error);
  } finally {
    await session.close();
  }
}

function toNumber(value: unknown): number {
  if (typeof value === "number") return value;
  if (value && typeof value === "object" && "toNumber" in value) {
    return (value as { toNumber: () => number }).toNumber();
  }
  return Number(value) || 0;
}
